In [1]:
import numpy as np
import os
from ECG.eager_ops import expected_gradients as eg
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
path = "./eval_data_10k/"

In [5]:
os.listdir(path)

['cnn_ph',
 'cnn_ph_eg',
 'cnn_pl',
 'cnn_pl_eg',
 'lstm_ph',
 'lstm_ph_eg',
 'lstm_pl',
 'lstm_pl_eg',
 'teset_x.npy',
 'teset_y.npy']

In [70]:
# Creating the confusion matrices for PH
cnn_ph_cv1 = np.load(path+ph_folders[0]+"/cms_cv1.npy")

In [4]:
def get_cmss(foldername, tname):
    if tname == "ph":
        cmss = []
        for i in range(1,11):
            cmss.append(np.load(path+foldername+"/cms_cv"+str(i)+".npy").reshape(1,8,8))
        cmss = np.concatenate(tuple(cmss), axis=0)
        return cmss
    elif tname == "pl":
        return np.load(path+foldername+"/cms.npy")

def get_results(foldername, tname):
    if tname == "ph":
        results = []
        for i in range(1,11):
            results.append(np.load(path+foldername+"/results_cv"+str(i)+".npy", allow_pickle=True)[1:6])
        return np.stack(tuple(results))
    elif tname == "pl":
        return np.load(path+foldername+"/results.npy", allow_pickle=True)


In [5]:
def make_cm(cmss, name):
    categories=['N','L','R','V','A','F','f','/']
    plt.figure(figsize=(10,7))
    sns.heatmap(cmss.mean(axis=0), annot=True, xticklabels=categories, yticklabels=categories)
    plt.title(name)
    plt.show()

### Beat Holdout

In [6]:
ph_folders = ['cnn_ph','cnn_ph_eg','lstm_ph']

In [79]:
# a = get_cmss("cnn_ph", "ph")
# b = get_cmss("lstm_ph", "ph")
# c = get_cmss('cnn_ph_eg', "ph")
# d = get_cmss('cnn_ph_eg', "ph")
# make_cm(a, "CNN - Beat holdout Confusion Matrix")
# make_cm(b, "LSTM - Beat holdout Confusion Matrix")
# make_cm(c, "CNN - Beat holdout with ECG Confusion Matrix")
# make_cm(d, "LSTM - Beat holdout with ECG Confusion Matrix")

### Patient Leave-out

In [ ]:
pl_folders = ['cnn_pl','cnn_pl_eg','lstm_pl','lstm_pl_eg']

In [110]:
# e = get_cmss("cnn_pl", "pl")
# f = get_cmss("lstm_pl", "pl")
# g = get_cmss('cnn_pl_eg', "pl")
# h = get_cmss('lstm_pl_eg', "pl")

# make_cm(e, "CNN - Patient leaveout Confusion Matrix")
# make_cm(g, "CNN - Patient leaveout with ECG Confusion Matrix")
# make_cm(f, "LSTM - Patient leaveout Confusion Matrix")
# make_cm(h, "LSTM - Patient leaveout with ECG Confusion Matrix")

In [7]:
d_r = get_results("cnn_pl", "pl")
e_r = get_results("lstm_pl", "pl")
f_r = get_results('cnn_pl_eg', "pl")
g_r = get_results('lstm_pl_eg', "pl")
print(d_r[3][1:6])
print(f_r[0][1:6])
print(e_r[0][1:6])
print(g_r[0][1:6])

[0.828 0.413 0.484 0.434 0.828]
[0.81 0.446 0.472 0.428 0.81]
[0.631 0.381 0.337 0.294 0.631]
[0.655 0.386 0.309 0.279 0.655]


In [11]:
def cal_eg(m, dx, dy): 
  test_d = tf.data.Dataset.from_tensor_slices((dx,dy))
  test_d = test_d.batch(200)
  att = None
  for i, (x_batch, y_batch) in enumerate(test_d):
    if i==0:
        att = eg(inputs=x_batch, labels=y_batch, model=m)
    else:
        att = np.append(att,eg(inputs=x_batch, labels=y_batch, model=m),axis=0)
  return att

def eg_att(foldername, tname):
    if tname=="ph":
        test_y = np.load("./eval_data_10k/teset_y.npy", allow_pickle=True)
        test_x = np.load("./eval_data_10k/teset_x.npy", allow_pickle=True)
        attributions = []
        for i in range(1,11):
            m = tf.keras.models.load_model(path+foldername+"/Model_cv"+str(i)+".h5")
            dx = test_x[i-1].reshape(-1, test_x[i-1].shape[1], 1).astype(np.float32)
            dy = tf.keras.utils.to_categorical(test_y[i-1].astype(np.float32))
            attributions.append(cal_eg(m, dx, dy))
        return attributions
    elif tname=="pl":
        test_c0 = np.genfromtxt('./Data/test_patients_fc.csv', delimiter=',')
        test_c1 = np.genfromtxt('./Data/test_patients_sc.csv', delimiter=',')
        test_x_c01 = np.concatenate((test_c0[:, :-2], test_c1[:, :-2]), axis=1)
        test_y_c01 = np.concatenate((test_c0[:, -2:], test_c0[:, -2:]), axis=1)
        dx = test_x_c01.reshape(-1, test_x_c01.shape[1], 1).astype('float32')
        dy = tf.keras.utils.to_categorical(test_y_c01[:,0])
        m = tf.keras.models.load_model(path+foldername+"/Model0.h5")
        return cal_eg(m, dx, dy)

In [9]:
test_c0 = np.genfromtxt('./Data/test_patients_fc.csv', delimiter=',')
test_c1 = np.genfromtxt('./Data/test_patients_sc.csv', delimiter=',')
test_x_c01 = np.concatenate((test_c0[:, :-2], test_c1[:, :-2]), axis=1)
test_y_c01 = np.concatenate((test_c0[:, -2:], test_c0[:, -2:]), axis=1)
dx = test_x_c01.reshape(-1, test_x_c01.shape[1], 1).astype('float32')
dy = tf.keras.utils.to_categorical(test_y_c01[:,0])
print(dy.shape, dx.shape)

(9902, 9) (9902, 920, 1)


In [14]:
m = tf.keras.models.load_model(path+"cnn_pl"+"/Model0.h5")
cal_eg(m, dx, dy).shape

(9902, 920, 1)